# Auto-provision the Prometheus datasource on Grafana startup.
# See https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST
